'use client';

import React from 'react';
import { format } from 'date-fns';
import { Timestamp } from 'firebase/firestore';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import type { EnrichedPresentation } from '@/types';

/** The change request (if any) that produced / last changed this presentation. */
export type PresentationSourceRequest = {
  id: string;
  repId: string;
  requestType: 'New Doctor' | 'Slide Change';
  selectedSlides: number[];
  createdAt: Timestamp;
  reviewedBy?: string;
  reviewedByName?: string;
  reviewedAt?: Timestamp;
};

type Props = {
  presentation: EnrichedPresentation | null;
  request: PresentationSourceRequest | null;
  /** uid -> display name, from listAllUsers */
  userNames: Map<string, string>;
  onClose: () => void;
};

const fmt = (ts?: Timestamp | null) => (ts ? format(ts.toDate(), 'PPP p') : '—');

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-0.5 py-2 sm:flex-row sm:items-start sm:gap-4">
      <dt className="w-40 shrink-0 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</dt>
      <dd className="min-w-0 break-words text-sm">{children}</dd>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="rounded-lg border bg-muted/20 px-4 py-2">
      <h3 className="pt-1 text-sm font-semibold">{title}</h3>
      <dl className="divide-y">{children}</dl>
    </section>
  );
}

export function PresentationDetailsDialog({ presentation, request, userNames, onClose }: Props) {
  const nameOf = (uid?: string) => (uid ? userNames.get(uid) || 'Unknown user' : '—');
  const slides = presentation?.doctorSlides ?? [];

  return (
    <Dialog open={!!presentation} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-h-[90vh] max-w-xl overflow-y-auto">
        {presentation && (
          <>
            <DialogHeader>
              <DialogTitle>{presentation.doctorName}</DialogTitle>
              <DialogDescription>Presentation details and approval history</DialogDescription>
            </DialogHeader>

            <div className="space-y-4">
              <Section title="Presentation">
                <Row label="Doctor">{presentation.doctorName}</Row>
                <Row label="City">{presentation.doctorCity}</Row>
                <Row label="District">{presentation.doctorDistrict}</Row>
                <Row label="Status">
                  <Badge variant="secondary" className="capitalize">{presentation.status}</Badge>
                  {presentation.error && <span className="ml-2 text-destructive">{presentation.error}</span>}
                </Row>
                <Row label="Slides">
                  {slides.length > 0 ? `${slides.length} slides — ${slides.join(', ')}` : '—'}
                </Row>
                <Row label="Last generated">{fmt(presentation.updatedAt)}</Row>
                <Row label="Generated by">{nameOf(presentation.updatedBy)}</Row>
              </Section>

              {request ? (
                <Section title="Change request">
                  <Row label="Request type">{request.requestType}</Row>
                  <Row label="Requested by">{nameOf(request.repId)}</Row>
                  <Row label="Requested at">{fmt(request.createdAt)}</Row>
                  <Row label="Approved by">
                    {request.reviewedByName || nameOf(request.reviewedBy)}
                    {!request.reviewedBy && !request.reviewedByName && (
                      <span className="text-muted-foreground"> (not recorded — approved before tracking was added)</span>
                    )}
                  </Row>
                  <Row label="Approved at">{fmt(request.reviewedAt)}</Row>
                  <Row label="Slides requested">
                    {request.selectedSlides?.length ? request.selectedSlides.join(', ') : '—'}
                  </Row>
                </Section>
              ) : (
                <Section title="Origin">
                  <Row label="Created">Added directly by an admin — no field request involved.</Row>
                </Section>
              )}
            </div>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}
